CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    full_name VARCHAR,
    date_of_birth DATE,
    username VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
